name: schulplaner_addons
description: Simply the flutter workflow:)
version: 0.1.0
author: Felix Weuthen
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  bloc:
    path: ../bloc
  #GENERAL
  uuid: ^3.0.0
  #FILES AND IMAGES
  cached_network_image: 3.0.0-nullsafety
  path_provider: ^2.0.1
  image: 3.0.1
  image_cropper: ^1.4.0
  flutter_image_compress: ^0.7.0
  image_picker: ^0.7.2
  file_picker: ^3.0.0
  photo_view: ^0.11.1
  #FIREBASE
  firebase_storage: ^8.0.0
  cloud_firestore: 1.0.1
  #MORE
  url_launcher: 6.0.2
  universal_io: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
  plugin_platform_interface: ^2.0.0
  petitparser: ^4.0.2
  xml: ^5.0.2
  crypto: ^3.0.0
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1


flutter: