name: schulplaner8
description: A new Flutter project.
publish_to: none
version: 10.0.1+611

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  schulplaner_addons:
    path: ../packages/schulplaner_addons
  schulplaner_widgets:
    path: ../packages/schulplaner_widgets
  bloc:
    path: ../packages/bloc
  authentification:
    path: ../packages/authentification
  universal_commons:
    path: ../packages/universal_commons
  schulplaner_translations:
    path: ../packages/schulplaner_translations
  date:
    path: ../packages/date
  app_functions:
    path: ../packages/app_functions
  schulplaner_functions:
    path: ../packages/schulplaner_functions
  schulplaner_models:
    path: ../packages/schulplaner_models
  schulplaner_navigation:
    path: ../packages/schulplaner_navigation
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: 2.0.3
  cupertino_icons: 1.0.2

  #GOOGLE
  cloud_firestore: 1.0.0
  firebase_auth: 1.0.0
  firebase_messaging: 9.0.0
  firebase_storage: 8.0.0
  firebase_analytics: 7.1.0
  firebase_database: 6.1.0
  firebase_performance: 0.6.0
  firebase_crashlytics: 1.0.0
  firebase_dynamic_links: ^0.8.0

  intl: ^0.17.0-nullsafety.2
  intl_translation: 0.17.10+1
  rxdart: ^0.26.0
  
  community_material_icon: 5.9.55
  font_awesome_flutter: ^8.8.1
  color: 2.1.1
  flutter_material_color_picker: 1.0.5
  diff_match_patch: 0.3.0
  qr_flutter: 3.2.0
  device_info: 2.0.0
  url_launcher: 6.0.2
  decimal: 1.0.0
  share: 2.0.0
  tuple: 2.0.0-nullsafety.0
  launch_review: 2.0.0
  flutter_image_compress: 0.7.0
  photo_view: 0.10.3
  path_provider: 2.0.1
  cached_network_image: 3.0.0-nullsafety
  flutter_cache_manager: 3.0.0-nullsafety.1
  after_layout: 1.0.7+2
  auto_size_text: 2.1.0
  filesize: 1.0.4
  image: 3.0.1
  dots_indicator: ^1.2.0
  timeago: ^3.0.1
  fl_chart: ^0.20.1
  percent_indicator: ^2.1.9+1
  printing: ^5.0.2
  pdf: ^3.0.1
  universal_io: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
  qr: ^2.0.0
  plugin_platform_interface: ^2.0.0
  firebase_auth_oauth:
    git: 
      url: https://github.com/treeder/firebase_auth_oauth.git
      ref: non-existant-deps
      path: firebase_auth_oauth
  firebase_auth_oauth_web:
    git: 
      url: https://github.com/treeder/firebase_auth_oauth.git
      ref: non-existant-deps
      path: firebase_auth_oauth_web
  firebase_auth_oauth_platform_interface:
    git: 
      url: https://github.com/treeder/firebase_auth_oauth.git
      ref: non-existant-deps
      path: firebase_auth_oauth_platform_interface
  firebase: ^9.0.0
  petitparser: ^4.0.2
  xml: ^5.0.2
  crypto: ^3.0.0-nullsafety


flutter:
  uses-material-design: true
  assets:
    - assets/about_me_felix.jpg