name: schulplaner8
description: A new Flutter project.
publish_to: none
version: 10.0.1+611

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  schulplaner_addons:
    path: ../packages/schulplaner_addons
  schulplaner_widgets:
    path: ../packages/schulplaner_widgets
  bloc:
    path: ../packages/bloc
  authentification:
    path: ../packages/authentification
  universal_commons:
    path: ../packages/universal_commons
  schulplaner_translations:
    path: ../packages/schulplaner_translations
  date:
    path: ../packages/date
  app_functions:
    path: ../packages/app_functions
  schulplaner_functions:
    path: ../packages/schulplaner_functions
  schulplaner_models:
    path: ../packages/schulplaner_models
  schulplaner_navigation:
    path: ../packages/schulplaner_navigation
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: 0.5.12+4
  cupertino_icons: 1.0.1+1

  #GOOGLE
  cloud_firestore: 0.14.4
  firebase_auth: 0.18.4+1
  firebase_messaging: 7.0.3
  firebase_storage: 5.2.0
  firebase_analytics: 6.3.0
  firebase_database: 4.4.0
  firebase_performance: 0.4.3
  firebase_crashlytics: 0.2.4
  firebase_dynamic_links: ^0.6.3

  intl: ^0.17.0-nullsafety.2
  intl_translation: 0.17.10+1
  rxdart: ^0.24.1
  
  community_material_icon: 5.8.55
  color: 2.1.1
  flutter_material_color_picker: 1.0.5
  diff_match_patch: 0.3.0
  qr_flutter: 3.2.0
  device_info: 1.0.0
  url_launcher: 5.7.10
  decimal: 0.3.5
  share: 0.6.5+4
  tuple: 1.0.3
  launch_review: 2.0.0
  flutter_image_compress: 0.7.0
  photo_view: 0.10.3
  path_provider: 1.6.24
  cached_network_image: 2.4.1
  flutter_cache_manager: 2.0.0
  after_layout: 1.0.7+2
  auto_size_text: 2.1.0
  avataaar_image: 1.0.8
  filesize: 1.0.4
  image: 2.1.19
  dots_indicator: ^1.2.0
  timeago: ^2.0.28
  fl_chart: ^0.11.1
  percent_indicator: ^2.1.8
  printing: ^3.7.1
  pdf: ^1.12.0
  universal_io: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
  firebase_auth:
    git: 
      url: https://github.com/FirebaseExtended/flutterfire.git
      ref: "@russell/constants-app-initialise"
      path: packages/firebase_auth/firebase_auth
  firebase_auth_platform_interface:
    git: 
      url: https://github.com/FirebaseExtended/flutterfire.git
      ref: "@russell/constants-app-initialise"
      path: packages/firebase_auth/firebase_auth_platform_interface
  firebase_auth_web:
    git: 
      url: https://github.com/FirebaseExtended/flutterfire.git
      ref: "@russell/constants-app-initialise"
      path: packages/firebase_auth/firebase_auth_web
  firebase_core_platform_interface:
    git: 
      url: https://github.com/FirebaseExtended/flutterfire.git
      ref: "@russell/constants-app-initialise"
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_core_web:
    git: 
      url: https://github.com/FirebaseExtended/flutterfire.git
      ref: "@russell/constants-app-initialise"
      path: packages/firebase_core/firebase_core_web

flutter:
  uses-material-design: true
  assets:
    - assets/about_me_felix.jpg