name: authentification
description:  Authentifizierung für die Schulplaner App
version: 0.0.1
author: Felix Weuthen
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.26.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../bloc
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  universal_commons:
    path: ../universal_commons
  firebase_auth: 1.0.0
  google_sign_in: 5.0.0
  sign_in_with_apple: ^2.5.4
  firebase_auth_oauth: 0.2.4
  rxdart: ^0.26.0
  community_material_icon: 5.9.55

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
  firebase_auth_oauth:
    git: 
      url: https://github.com/treeder/firebase_auth_oauth.git
      ref: non-existant-deps
      path: firebase_auth_oauth
  firebase_auth_oauth_web:
    git: 
      url: https://github.com/treeder/firebase_auth_oauth.git
      ref: non-existant-deps
      path: firebase_auth_oauth_web
  firebase_auth_oauth_platform_interface:
    git: 
      url: https://github.com/treeder/firebase_auth_oauth.git
      ref: non-existant-deps
      path: firebase_auth_oauth_platform_interface
      
