name: schulplaner_website
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">2.12.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../packages/bloc
  design_utils:
    path: ../packages/design_utils
  cupertino_icons: ^1.0.2
  url_launcher: 6.0.3
  flutter_svg: ^0.21.0-nullsafety.0
  community_material_icon: ^5.9.55
  carousel_slider: ^4.0.0-nullsafety.0
  easy_dynamic_theme: ^2.0.0
  #url_strategy: 0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  shared_preferences: ^2.0.5
  plugin_platform_interface: ^2.0.0
  flutter_material_color_picker: 
    git:
      url: https://github.com/Bwolfs2/flutter_material_color_picker


flutter:
  uses-material-design: true
  assets:
    - assets/badges/
    - assets/screenshots/
    - assets/privacy_policy_schulplaner.pdf
