name: schulplaner_website
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../packages/bloc
  design_utils:
    path: ../packages/design_utils
  cupertino_icons: ^1.0.2
  url_launcher: 5.7.10
  flutter_svg: ^0.19.2+1
  community_material_icon: ^5.4.55
  native_pdf_renderer: ^2.4.0
  carousel_slider: ^3.0.0
  persist_theme: ^1.7.0
  provider: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  extended_image: 1.5.0-dev

flutter:
  uses-material-design: true
  assets:
    - assets/badges/
    - assets/screenshots/
    - assets/privacy_policy_schulplaner.pdf
